#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Programming
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKS")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    partial void InsertThuVien(ThuVien instance);
    partial void UpdateThuVien(ThuVien instance);
    partial void DeleteThuVien(ThuVien instance);
    partial void InsertReview(Review instance);
    partial void UpdateReview(Review instance);
    partial void DeleteReview(Review instance);
    partial void InsertTacGia(TacGia instance);
    partial void UpdateTacGia(TacGia instance);
    partial void DeleteTacGia(TacGia instance);
    partial void InsertTacPham(TacPham instance);
    partial void UpdateTacPham(TacPham instance);
    partial void DeleteTacPham(TacPham instance);
    partial void InsertTheLoai(TheLoai instance);
    partial void UpdateTheLoai(TheLoai instance);
    partial void DeleteTheLoai(TheLoai instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLKSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<ThuVien> ThuViens
		{
			get
			{
				return this.GetTable<ThuVien>();
			}
		}
		
		public System.Data.Linq.Table<Review> Reviews
		{
			get
			{
				return this.GetTable<Review>();
			}
		}
		
		public System.Data.Linq.Table<TacGia> TacGias
		{
			get
			{
				return this.GetTable<TacGia>();
			}
		}
		
		public System.Data.Linq.Table<TacPham> TacPhams
		{
			get
			{
				return this.GetTable<TacPham>();
			}
		}
		
		public System.Data.Linq.Table<TheLoai> TheLoais
		{
			get
			{
				return this.GetTable<TheLoai>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Check")]
		public ISingleResult<DangNhap_CheckResult> DangNhap_Check([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string uname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uname, pass);
			return ((ISingleResult<DangNhap_CheckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_Update")]
		public int ThuVien_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinhVuc", DbType="NVarChar(50)")] string linhVuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLV, linhVuc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Exist")]
		public ISingleResult<DangNhap_ExistResult> DangNhap_Exist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string uname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uname);
			return ((ISingleResult<DangNhap_ExistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Insert")]
		public int DangNhap_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string uname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uname, pass, hoten, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_Delete")]
		public int Review_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSach", DbType="NVarChar(50)")] string maSach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSach);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_Insert")]
		public int Review_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSach", DbType="NVarChar(50)")] string maSach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSach", DbType="NVarChar(50)")] string tenSach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Maloai", DbType="NVarChar(50)")] string maloai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MoTa", DbType="NVarChar(MAX)")] string moTa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDungRv", DbType="NVarChar(MAX)")] string noiDungRv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HinhRv", DbType="NVarChar(50)")] string hinhRv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSach, tenSach, maloai, moTa, noiDungRv, hinhRv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_SelectAll")]
		public ISingleResult<Review_SelectAllResult> Review_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Review_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_Update")]
		public int Review_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSach", DbType="NVarChar(50)")] string maSach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSach", DbType="NVarChar(50)")] string tenSach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Maloai", DbType="NVarChar(50)")] string maloai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MoTa", DbType="NVarChar(MAX)")] string moTa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDungRv", DbType="NVarChar(MAX)")] string noiDungRv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HinhRv", DbType="NVarChar(50)")] string hinhRv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSach, tenSach, maloai, moTa, noiDungRv, hinhRv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_Delete")]
		public int TacGia_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTG);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_Insert")]
		public int TacGia_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTG", DbType="NVarChar(50)")] string tenTG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDung", DbType="NVarChar(MAX)")] string noiDung, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HinhAnh", DbType="NVarChar(50)")] string hinhAnh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamSinh", DbType="NVarChar(50)")] string namSinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTG, tenTG, noiDung, hinhAnh, namSinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_SelectAll")]
		public ISingleResult<TacGia_SelectAllResult> TacGia_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TacGia_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_SelectMaTG")]
		public ISingleResult<TacGia_SelectMaTGResult> TacGia_SelectMaTG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTG);
			return ((ISingleResult<TacGia_SelectMaTGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_SelectMaTP")]
		public ISingleResult<TacGia_SelectMaTPResult> TacGia_SelectMaTP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTP", DbType="NVarChar(50)")] string maTP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTP);
			return ((ISingleResult<TacGia_SelectMaTPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_SelectRanDom")]
		public ISingleResult<TacGia_SelectRanDomResult> TacGia_SelectRanDom()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TacGia_SelectRanDomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_SelNamePic")]
		public ISingleResult<TacGia_SelNamePicResult> TacGia_SelNamePic()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TacGia_SelNamePicResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacGia_Update")]
		public int TacGia_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTG", DbType="NVarChar(50)")] string tenTG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDung", DbType="NVarChar(MAX)")] string noiDung, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HinhAnh", DbType="NVarChar(50)")] string hinhAnh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamSinh", DbType="NVarChar(50)")] string namSinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTG, tenTG, noiDung, hinhAnh, namSinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_Delete")]
		public int TacPham_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTP", DbType="NVarChar(50)")] string maTP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_Insert")]
		public int TacPham_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTP", DbType="NVarChar(50)")] string maTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTP", DbType="NVarChar(50)")] string tenTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamSX", DbType="NVarChar(50)")] string namSX, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDungTP", DbType="NVarChar(MAX)")] string noiDungTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HinhTP", DbType="NVarChar(50)")] string hinhTP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTP, tenTP, maTG, maLV, namSX, noiDungTP, hinhTP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_SelectAll")]
		public ISingleResult<TacPham_SelectAllResult> TacPham_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TacPham_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_SelectMaTP")]
		public ISingleResult<TacPham_SelectMaTPResult> TacPham_SelectMaTP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTP", DbType="NVarChar(50)")] string maTP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTP);
			return ((ISingleResult<TacPham_SelectMaTPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_SelectRanDom")]
		public ISingleResult<TacPham_SelectRanDomResult> TacPham_SelectRanDom([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTP", DbType="NVarChar(50)")] string maTP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTP);
			return ((ISingleResult<TacPham_SelectRanDomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_SelectThuVien")]
		public ISingleResult<TacPham_SelectThuVienResult> TacPham_SelectThuVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLV);
			return ((ISingleResult<TacPham_SelectThuVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_SelectTP")]
		public ISingleResult<TacPham_SelectTPResult> TacPham_SelectTP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTG);
			return ((ISingleResult<TacPham_SelectTPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_SelNamePic")]
		public ISingleResult<TacPham_SelNamePicResult> TacPham_SelNamePic()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TacPham_SelNamePicResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TacPham_Update")]
		public int TacPham_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTP", DbType="NVarChar(50)")] string maTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTP", DbType="NVarChar(50)")] string tenTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTG", DbType="NVarChar(50)")] string maTG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamSX", DbType="NVarChar(50)")] string namSX, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDungTP", DbType="NVarChar(MAX)")] string noiDungTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HinhTP", DbType="NVarChar(50)")] string hinhTP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTP, tenTP, maTG, maLV, namSX, noiDungTP, hinhTP);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TheLoai_Delete")]
		public int TheLoai_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTL", DbType="NVarChar(50)")] string maTL)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTL);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TheLoai_Insert")]
		public int TheLoai_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLoai", DbType="NVarChar(50)")] string maLoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLoai", DbType="NVarChar(50)")] string tenLoai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLoai, tenLoai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TheLoai_SelectAll")]
		public ISingleResult<TheLoai_SelectAllResult> TheLoai_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TheLoai_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TheLoai_Update")]
		public int TheLoai_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTL", DbType="NVarChar(50)")] string maTL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenTL", DbType="NVarChar(50)")] string tenTL)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTL, tenTL);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_Delete")]
		public int ThuVien_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_Insert")]
		public int ThuVien_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinhVuc", DbType="NVarChar(50)")] string linhVuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLV, linhVuc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_SelectAll")]
		public ISingleResult<ThuVien_SelectAllResult> ThuVien_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ThuVien_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_SelectMaLV")]
		public ISingleResult<ThuVien_SelectMaLVResult> ThuVien_SelectMaLV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLV);
			return ((ISingleResult<ThuVien_SelectMaLVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_SelectRanDom")]
		public ISingleResult<ThuVien_SelectRanDomResult> ThuVien_SelectRanDom()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ThuVien_SelectRanDomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuVien_SelectTPLV")]
		public ISingleResult<ThuVien_SelectTPLVResult> ThuVien_SelectTPLV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLV", DbType="NVarChar(50)")] string maLV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLV);
			return ((ISingleResult<ThuVien_SelectTPLVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_SelNamePic")]
		public ISingleResult<Review_SelNamePicResult> Review_SelNamePic()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Review_SelNamePicResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_SelectRanDom")]
		public ISingleResult<Review_SelectRanDomResult> Review_SelectRanDom([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSach", DbType="NVarChar(50)")] string maSach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSach);
			return ((ISingleResult<Review_SelectRanDomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Review_SelectMaTP")]
		public ISingleResult<Review_SelectMaTPResult> Review_SelectMaTP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSach", DbType="NVarChar(50)")] string maSach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSach);
			return ((ISingleResult<Review_SelectMaTPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TheLoai_SelectSTL")]
		public ISingleResult<TheLoai_SelectSTLResult> TheLoai_SelectSTL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaLoai", DbType="NVarChar(50)")] string maLoai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLoai);
			return ((ISingleResult<TheLoai_SelectSTLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TheLoai_SelectMaTL")]
		public ISingleResult<TheLoai_SelectMaTLResult> TheLoai_SelectMaTL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaTL", DbType="NVarChar(50)")] string maTL)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maTL);
			return ((ISingleResult<TheLoai_SelectMaTLResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _Email;
		
		private string _HoTen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuVien")]
	public partial class ThuVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LinhVuc;
		
		private string _MaLV;
		
		private EntitySet<TacPham> _TacPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLinhVucChanging(string value);
    partial void OnLinhVucChanged();
    partial void OnMaLVChanging(string value);
    partial void OnMaLVChanged();
    #endregion
		
		public ThuVien()
		{
			this._TacPhams = new EntitySet<TacPham>(new Action<TacPham>(this.attach_TacPhams), new Action<TacPham>(this.detach_TacPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhVuc", DbType="NVarChar(50)")]
		public string LinhVuc
		{
			get
			{
				return this._LinhVuc;
			}
			set
			{
				if ((this._LinhVuc != value))
				{
					this.OnLinhVucChanging(value);
					this.SendPropertyChanging();
					this._LinhVuc = value;
					this.SendPropertyChanged("LinhVuc");
					this.OnLinhVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this.OnMaLVChanging(value);
					this.SendPropertyChanging();
					this._MaLV = value;
					this.SendPropertyChanged("MaLV");
					this.OnMaLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuVien_TacPham", Storage="_TacPhams", ThisKey="MaLV", OtherKey="MaLV")]
		public EntitySet<TacPham> TacPhams
		{
			get
			{
				return this._TacPhams;
			}
			set
			{
				this._TacPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TacPhams(TacPham entity)
		{
			this.SendPropertyChanging();
			entity.ThuVien = this;
		}
		
		private void detach_TacPhams(TacPham entity)
		{
			this.SendPropertyChanging();
			entity.ThuVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Review")]
	public partial class Review : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _MaLoai;
		
		private string _NoiDungRv;
		
		private string _HinhRv;
		
		private string _MoTa;
		
		private EntityRef<TheLoai> _TheLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnNoiDungRvChanging(string value);
    partial void OnNoiDungRvChanged();
    partial void OnHinhRvChanging(string value);
    partial void OnHinhRvChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public Review()
		{
			this._TheLoai = default(EntityRef<TheLoai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._TheLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungRv", DbType="NVarChar(MAX)")]
		public string NoiDungRv
		{
			get
			{
				return this._NoiDungRv;
			}
			set
			{
				if ((this._NoiDungRv != value))
				{
					this.OnNoiDungRvChanging(value);
					this.SendPropertyChanging();
					this._NoiDungRv = value;
					this.SendPropertyChanged("NoiDungRv");
					this.OnNoiDungRvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhRv", DbType="NVarChar(50)")]
		public string HinhRv
		{
			get
			{
				return this._HinhRv;
			}
			set
			{
				if ((this._HinhRv != value))
				{
					this.OnHinhRvChanging(value);
					this.SendPropertyChanging();
					this._HinhRv = value;
					this.SendPropertyChanged("HinhRv");
					this.OnHinhRvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_Review", Storage="_TheLoai", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public TheLoai TheLoai
		{
			get
			{
				return this._TheLoai.Entity;
			}
			set
			{
				TheLoai previousValue = this._TheLoai.Entity;
				if (((previousValue != value) 
							|| (this._TheLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheLoai.Entity = null;
						previousValue.Reviews.Remove(this);
					}
					this._TheLoai.Entity = value;
					if ((value != null))
					{
						value.Reviews.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("TheLoai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TacGia")]
	public partial class TacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTG;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		private EntitySet<TacPham> _TacPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnTenTGChanging(string value);
    partial void OnTenTGChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnNamSinhChanging(string value);
    partial void OnNamSinhChanged();
    #endregion
		
		public TacGia()
		{
			this._TacPhams = new EntitySet<TacPham>(new Action<TacPham>(this.attach_TacPhams), new Action<TacPham>(this.detach_TacPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this.OnTenTGChanging(value);
					this.SendPropertyChanging();
					this._TenTG = value;
					this.SendPropertyChanged("TenTG");
					this.OnTenTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TacGia_TacPham", Storage="_TacPhams", ThisKey="MaTG", OtherKey="MaTG")]
		public EntitySet<TacPham> TacPhams
		{
			get
			{
				return this._TacPhams;
			}
			set
			{
				this._TacPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TacPhams(TacPham entity)
		{
			this.SendPropertyChanging();
			entity.TacGia = this;
		}
		
		private void detach_TacPhams(TacPham entity)
		{
			this.SendPropertyChanging();
			entity.TacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TacPham")]
	public partial class TacPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG;
		
		private string _MaLV;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		private EntityRef<ThuVien> _ThuVien;
		
		private EntityRef<TacGia> _TacGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTPChanging(string value);
    partial void OnMaTPChanged();
    partial void OnTenTPChanging(string value);
    partial void OnTenTPChanged();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnMaLVChanging(string value);
    partial void OnMaLVChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnNoiDungTPChanging(string value);
    partial void OnNoiDungTPChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnHinhTPChanging(string value);
    partial void OnHinhTPChanged();
    #endregion
		
		public TacPham()
		{
			this._ThuVien = default(EntityRef<ThuVien>);
			this._TacGia = default(EntityRef<TacGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this.OnMaTPChanging(value);
					this.SendPropertyChanging();
					this._MaTP = value;
					this.SendPropertyChanged("MaTP");
					this.OnMaTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this.OnTenTPChanging(value);
					this.SendPropertyChanging();
					this._TenTP = value;
					this.SendPropertyChanged("TenTP");
					this.OnTenTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					if (this._TacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50)")]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					if (this._ThuVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLVChanging(value);
					this.SendPropertyChanging();
					this._MaLV = value;
					this.SendPropertyChanged("MaLV");
					this.OnMaLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this.OnNoiDungTPChanging(value);
					this.SendPropertyChanging();
					this._NoiDungTP = value;
					this.SendPropertyChanged("NoiDungTP");
					this.OnNoiDungTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this.OnHinhTPChanging(value);
					this.SendPropertyChanging();
					this._HinhTP = value;
					this.SendPropertyChanged("HinhTP");
					this.OnHinhTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuVien_TacPham", Storage="_ThuVien", ThisKey="MaLV", OtherKey="MaLV", IsForeignKey=true)]
		public ThuVien ThuVien
		{
			get
			{
				return this._ThuVien.Entity;
			}
			set
			{
				ThuVien previousValue = this._ThuVien.Entity;
				if (((previousValue != value) 
							|| (this._ThuVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuVien.Entity = null;
						previousValue.TacPhams.Remove(this);
					}
					this._ThuVien.Entity = value;
					if ((value != null))
					{
						value.TacPhams.Add(this);
						this._MaLV = value.MaLV;
					}
					else
					{
						this._MaLV = default(string);
					}
					this.SendPropertyChanged("ThuVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TacGia_TacPham", Storage="_TacGia", ThisKey="MaTG", OtherKey="MaTG", IsForeignKey=true)]
		public TacGia TacGia
		{
			get
			{
				return this._TacGia.Entity;
			}
			set
			{
				TacGia previousValue = this._TacGia.Entity;
				if (((previousValue != value) 
							|| (this._TacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TacGia.Entity = null;
						previousValue.TacPhams.Remove(this);
					}
					this._TacGia.Entity = value;
					if ((value != null))
					{
						value.TacPhams.Add(this);
						this._MaTG = value.MaTG;
					}
					else
					{
						this._MaTG = default(string);
					}
					this.SendPropertyChanged("TacGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheLoai")]
	public partial class TheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<Review> _Reviews;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public TheLoai()
		{
			this._Reviews = new EntitySet<Review>(new Action<Review>(this.attach_Reviews), new Action<Review>(this.detach_Reviews));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_Review", Storage="_Reviews", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<Review> Reviews
		{
			get
			{
				return this._Reviews;
			}
			set
			{
				this._Reviews.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = this;
		}
		
		private void detach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = null;
		}
	}
	
	public partial class DangNhap_CheckResult
	{
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _Email;
		
		private string _HoTen;
		
		public DangNhap_CheckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this._PassWord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
	}
	
	public partial class DangNhap_ExistResult
	{
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _Email;
		
		private string _HoTen;
		
		public DangNhap_ExistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this._PassWord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
	}
	
	public partial class Review_SelectAllResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _MaLoai;
		
		private string _NoiDungRv;
		
		private string _HinhRv;
		
		private string _MoTa;
		
		public Review_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this._MaLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungRv", DbType="NVarChar(MAX)")]
		public string NoiDungRv
		{
			get
			{
				return this._NoiDungRv;
			}
			set
			{
				if ((this._NoiDungRv != value))
				{
					this._NoiDungRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhRv", DbType="NVarChar(50)")]
		public string HinhRv
		{
			get
			{
				return this._HinhRv;
			}
			set
			{
				if ((this._HinhRv != value))
				{
					this._HinhRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(10)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
	}
	
	public partial class TacGia_SelectAllResult
	{
		
		private string _MaTG;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacGia_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacGia_SelectMaTGResult
	{
		
		private string _MaTG;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacGia_SelectMaTGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacGia_SelectMaTPResult
	{
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG;
		
		private string _MaLV;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		private string _MaTG1;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacGia_SelectMaTPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50)")]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this._NoiDungTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG1
		{
			get
			{
				return this._MaTG1;
			}
			set
			{
				if ((this._MaTG1 != value))
				{
					this._MaTG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacGia_SelectRanDomResult
	{
		
		private string _MaTG;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacGia_SelectRanDomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacGia_SelNamePicResult
	{
		
		private string _TenTG;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		private string _MaTG;
		
		public TacGia_SelNamePicResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
	}
	
	public partial class TacPham_SelectAllResult
	{
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG;
		
		private string _MaLV;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		public TacPham_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50)")]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this._NoiDungTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
	}
	
	public partial class TacPham_SelectMaTPResult
	{
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG;
		
		private string _MaLV;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		private string _MaTG1;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacPham_SelectMaTPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50)")]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this._NoiDungTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG1
		{
			get
			{
				return this._MaTG1;
			}
			set
			{
				if ((this._MaTG1 != value))
				{
					this._MaTG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacPham_SelectRanDomResult
	{
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG;
		
		private string _MaLV;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		private string _MaTG1;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacPham_SelectRanDomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50)")]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this._NoiDungTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG1
		{
			get
			{
				return this._MaTG1;
			}
			set
			{
				if ((this._MaTG1 != value))
				{
					this._MaTG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacPham_SelectThuVienResult
	{
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG;
		
		private string _MaLV;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		private string _MaTG1;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		public TacPham_SelectThuVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50)")]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this._NoiDungTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG1
		{
			get
			{
				return this._MaTG1;
			}
			set
			{
				if ((this._MaTG1 != value))
				{
					this._MaTG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
	}
	
	public partial class TacPham_SelectTPResult
	{
		
		private string _TenTP;
		
		private string _MaTP;
		
		public TacPham_SelectTPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
	}
	
	public partial class TacPham_SelNamePicResult
	{
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _HinhTP;
		
		private string _TenTG;
		
		private string _MaTG;
		
		private string _NamSX;
		
		public TacPham_SelNamePicResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
	}
	
	public partial class TheLoai_SelectAllResult
	{
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		public TheLoai_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this._MaLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this._TenLoai = value;
				}
			}
		}
	}
	
	public partial class ThuVien_SelectAllResult
	{
		
		private string _LinhVuc;
		
		private string _MaLV;
		
		public ThuVien_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhVuc", DbType="NVarChar(50)")]
		public string LinhVuc
		{
			get
			{
				return this._LinhVuc;
			}
			set
			{
				if ((this._LinhVuc != value))
				{
					this._LinhVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
	}
	
	public partial class ThuVien_SelectMaLVResult
	{
		
		private string _LinhVuc;
		
		private string _MaLV;
		
		public ThuVien_SelectMaLVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhVuc", DbType="NVarChar(50)")]
		public string LinhVuc
		{
			get
			{
				return this._LinhVuc;
			}
			set
			{
				if ((this._LinhVuc != value))
				{
					this._LinhVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
	}
	
	public partial class ThuVien_SelectRanDomResult
	{
		
		private string _LinhVuc;
		
		private string _MaLV;
		
		public ThuVien_SelectRanDomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhVuc", DbType="NVarChar(50)")]
		public string LinhVuc
		{
			get
			{
				return this._LinhVuc;
			}
			set
			{
				if ((this._LinhVuc != value))
				{
					this._LinhVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
	}
	
	public partial class ThuVien_SelectTPLVResult
	{
		
		private string _LinhVuc;
		
		private string _MaLV;
		
		private string _MaTG;
		
		private string _TenTG;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _NamSinh;
		
		private string _MaTP;
		
		private string _TenTP;
		
		private string _MaTG1;
		
		private string _MaLV1;
		
		private string _NamSX;
		
		private string _NoiDungTP;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _HinhTP;
		
		public ThuVien_SelectTPLVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhVuc", DbType="NVarChar(50)")]
		public string LinhVuc
		{
			get
			{
				return this._LinhVuc;
			}
			set
			{
				if ((this._LinhVuc != value))
				{
					this._LinhVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLV
		{
			get
			{
				return this._MaLV;
			}
			set
			{
				if ((this._MaLV != value))
				{
					this._MaLV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					this._MaTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTG", DbType="NVarChar(50)")]
		public string TenTG
		{
			get
			{
				return this._TenTG;
			}
			set
			{
				if ((this._TenTG != value))
				{
					this._TenTG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="NVarChar(50)")]
		public string NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this._MaTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(50)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this._TenTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG1", DbType="NVarChar(50)")]
		public string MaTG1
		{
			get
			{
				return this._MaTG1;
			}
			set
			{
				if ((this._MaTG1 != value))
				{
					this._MaTG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLV1", DbType="NVarChar(50)")]
		public string MaLV1
		{
			get
			{
				return this._MaLV1;
			}
			set
			{
				if ((this._MaLV1 != value))
				{
					this._MaLV1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(50)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this._NamSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTP", DbType="NVarChar(MAX)")]
		public string NoiDungTP
		{
			get
			{
				return this._NoiDungTP;
			}
			set
			{
				if ((this._NoiDungTP != value))
				{
					this._NoiDungTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhTP", DbType="NVarChar(50)")]
		public string HinhTP
		{
			get
			{
				return this._HinhTP;
			}
			set
			{
				if ((this._HinhTP != value))
				{
					this._HinhTP = value;
				}
			}
		}
	}
	
	public partial class Review_SelNamePicResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _HinhRv;
		
		private string _MoTa;
		
		public Review_SelNamePicResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhRv", DbType="NVarChar(50)")]
		public string HinhRv
		{
			get
			{
				return this._HinhRv;
			}
			set
			{
				if ((this._HinhRv != value))
				{
					this._HinhRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
	}
	
	public partial class Review_SelectRanDomResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _MaLoai;
		
		private string _NoiDungRv;
		
		private string _HinhRv;
		
		private string _MoTa;
		
		public Review_SelectRanDomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this._MaLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungRv", DbType="NVarChar(MAX)")]
		public string NoiDungRv
		{
			get
			{
				return this._NoiDungRv;
			}
			set
			{
				if ((this._NoiDungRv != value))
				{
					this._NoiDungRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhRv", DbType="NVarChar(50)")]
		public string HinhRv
		{
			get
			{
				return this._HinhRv;
			}
			set
			{
				if ((this._HinhRv != value))
				{
					this._HinhRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
	}
	
	public partial class Review_SelectMaTPResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _MaLoai;
		
		private string _NoiDungRv;
		
		private string _HinhRv;
		
		private string _MoTa;
		
		public Review_SelectMaTPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this._MaLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungRv", DbType="NVarChar(MAX)")]
		public string NoiDungRv
		{
			get
			{
				return this._NoiDungRv;
			}
			set
			{
				if ((this._NoiDungRv != value))
				{
					this._NoiDungRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhRv", DbType="NVarChar(50)")]
		public string HinhRv
		{
			get
			{
				return this._HinhRv;
			}
			set
			{
				if ((this._HinhRv != value))
				{
					this._HinhRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
	}
	
	public partial class TheLoai_SelectSTLResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _MaLoai;
		
		private string _NoiDungRv;
		
		private string _HinhRv;
		
		private string _MoTa;
		
		private string _MaLoai1;
		
		private string _TenLoai;
		
		public TheLoai_SelectSTLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this._MaLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungRv", DbType="NVarChar(MAX)")]
		public string NoiDungRv
		{
			get
			{
				return this._NoiDungRv;
			}
			set
			{
				if ((this._NoiDungRv != value))
				{
					this._NoiDungRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhRv", DbType="NVarChar(50)")]
		public string HinhRv
		{
			get
			{
				return this._HinhRv;
			}
			set
			{
				if ((this._HinhRv != value))
				{
					this._HinhRv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLoai1
		{
			get
			{
				return this._MaLoai1;
			}
			set
			{
				if ((this._MaLoai1 != value))
				{
					this._MaLoai1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this._TenLoai = value;
				}
			}
		}
	}
	
	public partial class TheLoai_SelectMaTLResult
	{
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		public TheLoai_SelectMaTLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this._MaLoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this._TenLoai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
